=== DSIC2024-TeamB5/SAMS/OperationController/bin/NOM.xsd
<?xml version="1.0" encoding="euc-kr" ?>
<!-- NOM schema version 1.01
     # Revision History
	- 1.01 : 복합타입의 encoding 방식을 정의할 수 있는 encodingType 필드 추가
-->
<xs:schema xmlns:nom="lignex1.sw.nframework.NOM" elementFormDefault="qualified" targetNamespace="lignex1.sw.nframework.NOM"
	id="NOM" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Nex1ObjectModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="objects" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="object">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="attribute">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required" />
												<xs:attribute name="size" type="xs:integer" use="optional" />
												<xs:attribute name="fixedLength" type="xs:integer" use="optional" />
												<xs:attribute name="nameNotes" type="xs:string" use="optional" />
												<xs:attribute name="dataType" type="xs:string" use="required" />
												<xs:attribute name="indicatorLength" use="optional" >
												    <xs:simpleType>
													    <xs:restriction base="xs:integer">
														    <xs:pattern value="0|1|2|4|8|-1|-2|-4|-8" />
													    </xs:restriction>
												    </xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="(0X|0x)[0-9a-fA-F]+|0[0-9]+|[0-9]+" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="nameNotes" type="xs:string" use="optional" />
									<xs:attribute name="sharing" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="Publish|Subscribe|PublishSubscribe|Neither" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="orderType" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="TimeStamp|Receive" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="alignment" type="xs:boolean" use="optional" />
									<xs:attribute name="period" type="xs:integer" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
        <xs:element name="interactions" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="interaction">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="parameter">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="size" type="xs:integer" use="optional" />
                        <xs:attribute name="fixedLength" type="xs:integer" use="optional" />
                        <xs:attribute name="nameNotes" type="xs:string" use="optional" />
                        <xs:attribute name="dataType" type="xs:string" use="required" />
                        <xs:attribute name="indicatorLength" use="optional" >
                          <xs:simpleType>
                            <xs:restriction base="xs:integer">
                              <xs:pattern value="0|1|2|4|8|-1|-2|-4|-8" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="id" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="(0X|0x)[0-9a-fA-F]+|0[0-9]+|[0-9]+" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="nameNotes" type="xs:string" use="optional" />
                  <xs:attribute name="sharing" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="Publish|Subscribe|PublishSubscribe|Neither" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="orderType" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="TimeStamp|Receive" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="alignment" type="xs:boolean" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
				<xs:element name="dataTypes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="basicTypes">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="basicType">
											<xs:annotation>
												<xs:documentation>size는 bit가 아닌 byte의 size를 입력해야 합니다. endian은 big, little, none 중에 하나를 입력해야 합니다. signed는 unsigned일 경우에 false를 입력하며 signed일 경우는 이 attribute를 생략해도 됩니다.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required" />
												<xs:attribute name="length" type="xs:integer" use="required" />
												<xs:attribute name="endian" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="little|big|none" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="signed" type="xs:boolean" />
												<xs:attribute name="type" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="Bool|Byte|Char|Short|Integer|Float|Double|String|Variable|FixedString|FixedDatum" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="note" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="enumerationTypes">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="enumerationType">
											<xs:complexType>
												<xs:sequence>
													<xs:element minOccurs="0" maxOccurs="unbounded" name="enumerator">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" use="required" />
															<xs:attribute name="value" type="xs:integer" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required" />
												<xs:attribute name="length" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:pattern value="1|2|4" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="nameNotes" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="complexTypes">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="complexType">
											<xs:complexType>
												<xs:sequence>
													<xs:element minOccurs="0" maxOccurs="unbounded" name="fieldType">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" use="required" />
															<xs:attribute name="nameNotes" type="xs:string" />
															<xs:attribute name="size" type="xs:integer" use="optional" />
															<xs:attribute name="fixedLength" type="xs:integer" use="optional" />
															<xs:attribute name="dataType" type="xs:string" use="required" />
															<xs:attribute name="indicatorLength" use="optional" >
															    <xs:simpleType>
																    <xs:restriction base="xs:integer">
																	    <xs:pattern value="0|1|2|4|8|-1|-2|-4|-8" />
																    </xs:restriction>
															    </xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-z_]([a-zA-Z0-9_])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="nameNotes" type="xs:string" />
												<xs:attribute name="encodingType" type="xs:string" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="notes">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="note">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="note" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]+.[0-9]+" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="date" type="xs:date" use="required" />
			<xs:attribute name="author" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DSIC2024-TeamB5/SAMS/OperationController/bin/CommandManager/CommandManager.xml
<?xml version="1.0" encoding="EUC-KR"?>
<NOM:Nex1ObjectModel xmlns:NOM="lignex1.sw.nframework.NOM" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lignex1.sw.nframework.NOM NOM.xsd" version="0.1" name="ATSCommunicationManager" date="2021-02-09" author="Junyong Shim, LIGNex1">
	<!--  object data  -->
	<NOM:objects>
		<!--  packet data  -->
	</NOM:objects>
	<!--  interaction data  -->
	<NOM:interactions>
		<NOM:interaction name="MSL_POSITION" id="1006" sharing="Neither" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MissileCurX" dataType="FloatBE"/>
			<NOM:parameter name="MissileCurY" dataType="FloatBE"/>
			<NOM:parameter name="IsShotDown" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="ATS_POSITION" id="1008" sharing="Subscribe" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="EnemyCurX" dataType="FloatBE"/>
			<NOM:parameter name="EnemyCurY" dataType="FloatBE"/>
		</NOM:interaction>
		<NOM:interaction name="ATS_POSITION_TO_MSL" id="2008" sharing="Publish" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="EnemyCurX" dataType="FloatBE"/>
			<NOM:parameter name="EnemyCurY" dataType="FloatBE"/>
		</NOM:interaction>
		<NOM:interaction name="SCN_DEPLOY" id="1001" sharing="Subscribe" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="EnemyInitX" dataType="FloatBE"/>
			<NOM:parameter name="EnemyInitY" dataType="FloatBE"/>
			<NOM:parameter name="EnemyDestX" dataType="FloatBE"/>
			<NOM:parameter name="EnemyDestY" dataType="FloatBE"/>
			<NOM:parameter name="EnemySpeed" dataType="FloatBE"/>
			<NOM:parameter name="EnemyType" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="EnemyAngle" dataType="FloatBE"/>
			<NOM:parameter name="MissileInitX" dataType="FloatBE"/>
			<NOM:parameter name="MissileInitY" dataType="FloatBE"/>
			<NOM:parameter name="MissileSpeed" dataType="FloatBE"/>
			<NOM:parameter name="RadarInitX" dataType="FloatBE"/>
			<NOM:parameter name="RadarInitY" dataType="FloatBE"/>
			<NOM:parameter name="LauncherInitX" dataType="FloatBE"/>
			<NOM:parameter name="LauncherInitY" dataType="FloatBE"/>
			<NOM:parameter name="LauncherStock" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="SIM_CONTROL" id="1002" sharing="Subscribe" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="OperationType" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="SIM_CONTROL_ATS_ROS" id="2002" sharing="Publish" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="OperationType" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="SIM_CONTROL_MSL_LOS" id="3002" sharing="Publish" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="OperationType" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="SIM_STATUS" id="1003" sharing="Publish" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="SimulatorState" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="ROS_DETECTION" id="1004" sharing="Publish" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="IsDetected" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="MSL_LAUNCH" id="1005" sharing="Subscribe" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
		<NOM:interaction name="ATS_SHOT_DOWN" id="1007" sharing="Neither" orderType="Receive" alignment="false">
			<NOM:parameter name="MessageId" dataType="UnsignedIntegerBE"/>
			<NOM:parameter name="MessageSize" dataType="UnsignedIntegerBE"/>
		</NOM:interaction>
	</NOM:interactions>
	<!--  data types  -->
	<NOM:dataTypes>
		<NOM:basicTypes>
			<NOM:basicType name="Boolean" length="1" endian="little" type="Bool" note="8bit value"/>
			<NOM:basicType name="IntegerBE" length="4" endian="big" type="Integer" note="32bit integer, big endian"/>
			<NOM:basicType name="Integer" length="4" endian="little" type="Integer" note="32bit integer, little endian"/>
			<NOM:basicType name="UnsignedIntegerBE" length="4" endian="big" signed="false" type="Integer" note="32bit unsigned integer, big endian"/>
			<NOM:basicType name="UnsignedInteger" length="4" endian="little" signed="false" type="Integer" note="32bit unsigned integer, little endian"/>
			<NOM:basicType name="Octet" length="1" endian="little" type="Byte" note="8bit value"/>
			<NOM:basicType name="ShortBE" length="2" endian="big" type="Short" note="16bit integer(short), big endian"/>
			<NOM:basicType name="Short" length="2" endian="little" type="Short" note="16bit integer(short), little endian"/>
			<NOM:basicType name="UnsignedShortBE" length="2" endian="big" signed="false" type="Short" note="16bit unsigned integer(short), big endian"/>
			<NOM:basicType name="UnsignedShort" length="2" endian="little" signed="false" type="Short" note="16bit unsigned integer(short), little endian"/>
			<NOM:basicType name="FloatBE" length="4" endian="big" type="Float" note="32bit float, big endian"/>
			<NOM:basicType name="Float" length="4" endian="little" type="Float" note="32bit float, little endian"/>
			<NOM:basicType name="DoubleBE" length="8" endian="big" type="Double" note="32bit double, little endian"/>
			<NOM:basicType name="Double" length="8" endian="little" type="Double" note="32bit double, little endian"/>
			<NOM:basicType name="Char" length="1" endian="none" type="Char" note="8bit char value"/>
			<NOM:basicType name="UnsignedChar" length="1" endian="none" signed="false" type="Char" note="8bit char value"/>
			<NOM:basicType name="Byte" length="1" endian="none" signed="false" type="Byte" note="8bit byte value"/>
			<NOM:basicType name="String" length="0" endian="none" signed="false" type="String" note="String"/>
			<NOM:basicType name="Var" length="0" endian="none" signed="false" type="Variable" note="Variable"/>
		</NOM:basicTypes>
		<NOM:enumerationTypes>
			<NOM:enumerationType name="TestEnum16" length="2">
				<NOM:enumerator name="Start" value="1"/>
				<NOM:enumerator name="Stop" value="2"/>
			</NOM:enumerationType>
		</NOM:enumerationTypes>
		<NOM:complexTypes>
			<NOM:complexType name="TestStruct">
				<NOM:fieldType name="X" dataType="FloatBE"/>
				<NOM:fieldType name="Y" dataType="FloatBE"/>
				<NOM:fieldType name="Z" dataType="FloatBE"/>
			</NOM:complexType>
		</NOM:complexTypes>
	</NOM:dataTypes>
	<NOM:notes> </NOM:notes>
</NOM:Nex1ObjectModel>

=== DSIC2024-TeamB5/SAMS/OperationController/bin/UIManager/UI.xml
<?xml version="1.0" encoding="euc-kr"?>
<NOM:Nex1ObjectModel xmlns:NOM="lignex1.sw.nframework.NOM" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lignex1.sw.nframework.NOM NOM.xsd"
    version="1.7" name="UI_NOM" date="2020-02-01" author="Junyong Shim, LIGNex1">
  <!-- object data -->
  <NOM:objects>
    <NOM:object name="ICD_Test1" id="111" nameNotes="ICD의 Test1 메시지" sharing="Subscribe" orderType="Receive" alignment="false">
      <NOM:attribute name="SystemTime1" nameNotes="Logging Time - sec"  dataType="UnsignedIntegerBE"/>
      <NOM:attribute name="SystemTime2" nameNotes="Logging Time - millisec"  dataType="UnsignedIntegerBE"/>
      <NOM:attribute name="Message1" nameNotes="수신 메시지 1" dataType="UnsignedIntegerBE"/>
      <NOM:attribute name="Message2" nameNotes="수신 메시지 2" dataType="UnsignedIntegerBE"/>
    </NOM:object>
  </NOM:objects>
  <!-- interaction data -->
  <NOM:interactions>
    <NOM:interaction name="GUI_Start" id="1001" nameNotes="시험정보 수집 시작" sharing="Publish" orderType="Receive" alignment="false">
      <NOM:parameter name="Message1" dataType="UnsignedIntegerBE" />
    </NOM:interaction>
  </NOM:interactions>
  <!-- data types -->
  <NOM:dataTypes>
    <NOM:basicTypes>
      <NOM:basicType name="Boolean" length="1" endian="little" type="Bool" note="8bit value"/>
      <NOM:basicType name="IntegerBE" length="4" endian="big" type="Integer" note="32bit integer, big endian"/>
      <NOM:basicType name="Integer" length="4" endian="little" type="Integer" note="32bit integer, little endian"/>
      <NOM:basicType name="UnsignedIntegerBE" length="4" endian="big" signed="false" type="Integer" note="32bit unsigned integer, big endian"/>
      <NOM:basicType name="UnsignedInteger" length="4" endian="little" signed="false" type="Integer" note="32bit unsigned integer, little endian"/>
      <NOM:basicType name="Octet" length="1" endian="little" type="Byte" note="8bit value"/>
      <NOM:basicType name="ShortBE" length="2" endian="big" type="Short" note="16bit integer(short), big endian"/>
      <NOM:basicType name="Short" length="2" endian="little" type="Short" note="16bit integer(short), little endian"/>
      <NOM:basicType name="UnsignedShortBE" length="2" endian="big" signed="false" type="Short" note="16bit unsigned integer(short), big endian"/>
      <NOM:basicType name="UnsignedShort" length="2" endian="little" signed="false" type="Short" note="16bit unsigned integer(short), little endian"/>
      <NOM:basicType name="FloatBE" length="4" endian="big" type="Float" note="32bit float, big endian"/>
      <NOM:basicType name="Float" length="4" endian="little" type="Float" note="32bit float, little endian"/>
      <NOM:basicType name="DoubleBE" length="8" endian="big" type="Double" note="32bit double, little endian"/>
      <NOM:basicType name="Double" length="8" endian="little" type="Double" note="32bit double, little endian"/>
      <NOM:basicType name="Char" length="1" endian="none" type="Char" note="8bit char value"/>
      <NOM:basicType name="UnsignedChar" length="1" endian="none" signed="false" type="Char" note="8bit char value"/>
      <NOM:basicType name="Byte" length="1" endian="none" signed="false" type="Byte" note="8bit byte value"/>
      <NOM:basicType name="String" length="0" endian="none" signed="false" type="String" note="String"/>
      <NOM:basicType name="Var" length="0" endian="none" signed="false" type="Variable" note="Variable"/>
    </NOM:basicTypes>
    <NOM:enumerationTypes>
      <NOM:enumerationType name="TestEnum16" length="2">
        <NOM:enumerator name="Start" value="1" />
        <NOM:enumerator name="Stop" value="2" />
      </NOM:enumerationType>
    </NOM:enumerationTypes>
    <NOM:complexTypes>
      <NOM:complexType name="TestStruct">
        <NOM:fieldType name="X" dataType="FloatBE" />
        <NOM:fieldType name="Y" dataType="FloatBE" />
        <NOM:fieldType name="Z" dataType="FloatBE" />
      </NOM:complexType>
    </NOM:complexTypes>
  </NOM:dataTypes>
  <NOM:notes>
  </NOM:notes>
</NOM:Nex1ObjectModel>
